from pathlib import Path

def r(path, old, new):
    p=Path(path); t=p.read_text()
    if old not in t: raise SystemExit(f'pattern not found in {path}: {old[:100]!r}')
    p.write_text(t.replace(old,new,1))

r('src/lib/appRegistry.ts','  /** Supplementary numeric/scale field IDs explicitly exposed to Patterns → Monthly. */\n  monthlyFieldIds?: string[];\n}','  /** Supplementary numeric/scale field IDs explicitly exposed to Patterns → Monthly. */\n  monthlyFieldIds?: string[];\n  /** Supplementary numeric/scale field IDs explicitly exposed to Patterns → Cycle. */\n  cycleFieldIds?: string[];\n}')
r('src/lib/appRegistry.ts','export function registryAdminMonthlyFieldsForFeature(\n  data: Pick<BixboData, "settings">,\n  featureId: RegistryFeatureId,\n): RegistryFieldDefinition[] {\n  const feature = activeAdminConfig(data)?.features?.[featureId];\n  const selected = new Set(feature?.monthlyFieldIds ?? []);\n  return [...(feature?.customFields ?? [])]\n    .filter((field) => field.enabled !== false && (field.kind === "number" || field.kind === "scale") && selected.has(field.id))\n    .sort((a, b) => a.order - b.order);\n}\n','export function registryAdminMonthlyFieldsForFeature(\n  data: Pick<BixboData, "settings">,\n  featureId: RegistryFeatureId,\n): RegistryFieldDefinition[] {\n  const feature = activeAdminConfig(data)?.features?.[featureId];\n  const selected = new Set(feature?.monthlyFieldIds ?? []);\n  return [...(feature?.customFields ?? [])]\n    .filter((field) => field.enabled !== false && (field.kind === "number" || field.kind === "scale") && selected.has(field.id))\n    .sort((a, b) => a.order - b.order);\n}\n\nexport function registryAdminCycleFieldsForFeature(\n  data: Pick<BixboData, "settings">,\n  featureId: RegistryFeatureId,\n): RegistryFieldDefinition[] {\n  const feature = activeAdminConfig(data)?.features?.[featureId];\n  const selected = new Set(feature?.cycleFieldIds ?? []);\n  return [...(feature?.customFields ?? [])]\n    .filter((field) => field.enabled !== false && (field.kind === "number" || field.kind === "scale") && selected.has(field.id))\n    .sort((a, b) => a.order - b.order);\n}\n')

r('src/components/CoreFeatureCustomFieldBuilder.tsx','    const monthlyFieldIds = (feature.monthlyFieldIds ?? []).filter((id) => id !== fieldId);\n    setDeviceAdminConfig({','    const monthlyFieldIds = (feature.monthlyFieldIds ?? []).filter((id) => id !== fieldId);\n    const cycleFieldIds = (feature.cycleFieldIds ?? []).filter((id) => id !== fieldId);\n    setDeviceAdminConfig({')
r('src/components/CoreFeatureCustomFieldBuilder.tsx','[featureId]: { ...feature, customFields: fields.filter((field) => field.id !== fieldId), heatmapFieldIds, monthlyFieldIds },','[featureId]: { ...feature, customFields: fields.filter((field) => field.id !== fieldId), heatmapFieldIds, monthlyFieldIds, cycleFieldIds },')
r('src/components/CoreFeatureCustomFieldBuilder.tsx','  const setMonthlyFieldEnabled = (featureId: RegistryFeatureId, fieldId: string, enabled: boolean) => {\n    const current = getDeviceAdminConfig();\n    const feature = current.features?.[featureId] ?? {};\n    const selected = new Set(feature.monthlyFieldIds ?? []);\n    if (enabled) selected.add(fieldId);\n    else selected.delete(fieldId);\n    setDeviceAdminConfig({\n      ...current,\n      enabled: true,\n      features: {\n        ...(current.features ?? {}),\n        [featureId]: { ...feature, monthlyFieldIds: [...selected] },\n      },\n    });\n  };\n','  const setMonthlyFieldEnabled = (featureId: RegistryFeatureId, fieldId: string, enabled: boolean) => {\n    const current = getDeviceAdminConfig();\n    const feature = current.features?.[featureId] ?? {};\n    const selected = new Set(feature.monthlyFieldIds ?? []);\n    if (enabled) selected.add(fieldId);\n    else selected.delete(fieldId);\n    setDeviceAdminConfig({ ...current, enabled: true, features: { ...(current.features ?? {}), [featureId]: { ...feature, monthlyFieldIds: [...selected] } } });\n  };\n\n  const setCycleFieldEnabled = (featureId: RegistryFeatureId, fieldId: string, enabled: boolean) => {\n    const current = getDeviceAdminConfig();\n    const feature = current.features?.[featureId] ?? {};\n    const selected = new Set(feature.cycleFieldIds ?? []);\n    if (enabled) selected.add(fieldId); else selected.delete(fieldId);\n    setDeviceAdminConfig({ ...current, enabled: true, features: { ...(current.features ?? {}), [featureId]: { ...feature, cycleFieldIds: [...selected] } } });\n  };\n')
r('src/components/CoreFeatureCustomFieldBuilder.tsx','                            <button\n                              type="button"\n                              onClick={() => setMonthlyFieldEnabled(feature.id, field.id, !(config.features?.[feature.id]?.monthlyFieldIds ?? []).includes(field.id))','                            <button\n                              type="button"\n                              onClick={() => setMonthlyFieldEnabled(feature.id, field.id, !(config.features?.[feature.id]?.monthlyFieldIds ?? []).includes(field.id))')
r('src/components/CoreFeatureCustomFieldBuilder.tsx','                            >\n                              Monthly {(config.features?.[feature.id]?.monthlyFieldIds ?? []).includes(field.id) ? t("On") : t("Off")}\n                            </button>\n                          </>','                            >\n                              Monthly {(config.features?.[feature.id]?.monthlyFieldIds ?? []).includes(field.id) ? t("On") : t("Off")}\n                            </button>\n                            <button type="button" onClick={() => setCycleFieldEnabled(feature.id, field.id, !(config.features?.[feature.id]?.cycleFieldIds ?? []).includes(field.id))} className={`rounded-full px-2 py-1 text-[8px] font-semibold ring-1 ${(config.features?.[feature.id]?.cycleFieldIds ?? []).includes(field.id) ? "bg-primary text-primary-foreground ring-primary/30" : "bg-tint text-muted-foreground ring-border"}`}>\n                              Cycle {(config.features?.[feature.id]?.cycleFieldIds ?? []).includes(field.id) ? t("On") : t("Off")}\n                            </button>\n                          </>')

r('src/lib/layoutRegistry.ts','    { id: "bodyChanges", label: "Body changes", order: 20 },\n  ],','    { id: "bodyChanges", label: "Body changes", order: 20 },\n    { id: "customMetrics", label: "Custom metrics", order: 30 },\n  ],')
r('src/routes/patterns.tsx','import { BIXBO_REGISTRY, getRegistryFeature, registryAdminMonthlyFieldsForFeature } from "@/lib/appRegistry";','import { BIXBO_REGISTRY, getRegistryFeature, registryAdminCycleFieldsForFeature, registryAdminMonthlyFieldsForFeature } from "@/lib/appRegistry";')
r('src/routes/patterns.tsx','  const commonFlow = phaseFlowMode(phaseBuckets.during, dayLogs);','  const adminCycleMetrics = BIXBO_REGISTRY.flatMap((featureBase) => {\n    const feature = getRegistryFeature(view, featureBase.id);\n    return registryAdminCycleFieldsForFeature(view, featureBase.id).map((field) => {\n      const metricFn = (log: DayLog) => {\n        const values = (log.adminFields?.[featureBase.id] ?? []).map((entry) => Number(entry.values[field.id])).filter((value) => Number.isFinite(value));\n        return avg(values);\n      };\n      return { id: `${featureBase.id}:${field.id}`, title: `${feature.label} · ${field.label}`, bars: [\n        { label: "Before", value: phaseAvg(phaseBuckets.before, dayLogs, metricFn) },\n        { label: "During", value: phaseAvg(phaseBuckets.during, dayLogs, metricFn) },\n        { label: "After", value: phaseAvg(phaseBuckets.after, dayLogs, metricFn) },\n      ] as PhaseBar[], max: field.kind === "scale" ? field.scale?.max : undefined, unit: field.kind === "scale" && field.scale?.max != null ? `/${field.scale.max}` : "" };\n    });\n  });\n\n  const commonFlow = phaseFlowMode(phaseBuckets.during, dayLogs);')
r('src/routes/patterns.tsx','          </div>\n        )}\n\n        {activeTab === "monthly" && (','            {adminCycleMetrics.length > 0 ? (\n              <CollapsibleSection layoutOrderValue={layoutOrder(view, "patterns.cycle", "customMetrics", 30)} title="Custom metrics" subtitle="Admin-created numeric and scale fields" defaultOpen={false}>\n                <Card title="Cycle phase — custom metrics" description="Admin-created values grouped by cycle phase.">\n                  <div className="mt-3 space-y-2.5">{adminCycleMetrics.map((metric) => <PhaseBarChart key={metric.id} title={metric.title} description="Average saved supplementary value by cycle phase." bars={metric.bars} max={metric.max} decimals={1} unit={metric.unit} />)}</div>\n                </Card>\n              </CollapsibleSection>\n            ) : null}\n          </div>\n        )}\n\n        {activeTab === "monthly" && (')

Path('src/lib/__tests__/admin-cycle-fields.test.ts').write_text('''import { describe, expect, it } from "bun:test";\nimport { registryAdminCycleFieldsForFeature, type AdminConfig } from "../appRegistry";\nimport { EMPTY } from "../storage";\nconst data=(config:AdminConfig)=>({ ...EMPTY, settings:{...EMPTY.settings,adminConfig:config}});\ndescribe("admin Cycle fields",()=>{it("filters opt-in numeric fields",()=>{expect(registryAdminCycleFieldsForFeature(data({features:{pain:{cycleFieldIds:["a","b"],customFields:[{id:"a",label:"A",kind:"number",order:1},{id:"b",label:"B",kind:"text",order:2}]}}}),"pain").map(f=>f.id)).toEqual(["a"]);});});\n''')
