from pathlib import Path
p = Path('src/components/CustomLogBuilder.tsx')
s = p.read_text()
old = '''  const patchField = (log: CustomLogDefinition, fieldId: string, patch: Partial<RegistryFieldDefinition>) => {\n    patchLog(log.id, {\n      fields: log.fields.map((field) => {\n        if (field.id !== fieldId) return field;\n        const next = { ...field, ...patch, id: field.id };\n        if (next.kind === "chips") {\n          const options = sanitizeOptions(next.options);\n          return { ...next, options, optionLabels: sanitizeOptionLabels(options, next.optionLabels), scale: undefined };\n        }\n        if (next.kind === "scale") return { ...next, options: undefined, optionLabels: undefined, scale: sanitizeScale(next.scale) };\n        return { ...next, options: undefined, optionLabels: undefined, scale: undefined };\n      }),\n    });\n  };'''
new = '''  const patchField = (log: CustomLogDefinition, fieldId: string, patch: Partial<RegistryFieldDefinition>) => {\n    let patchedField: RegistryFieldDefinition | undefined;\n    const fields = log.fields.map((field) => {\n      if (field.id !== fieldId) return field;\n      const next = { ...field, ...patch, id: field.id };\n      if (next.kind === "chips") {\n        const options = sanitizeOptions(next.options);\n        patchedField = { ...next, options, optionLabels: sanitizeOptionLabels(options, next.optionLabels), scale: undefined };\n      } else if (next.kind === "scale") {\n        patchedField = { ...next, options: undefined, optionLabels: undefined, scale: sanitizeScale(next.scale) };\n      } else {\n        patchedField = { ...next, options: undefined, optionLabels: undefined, scale: undefined };\n      }\n      return patchedField;\n    });\n    const selectedHeatmapFieldBecameInvalid =\n      log.heatmapFieldId === fieldId &&\n      (!patchedField || patchedField.enabled === false || (patchedField.kind !== "number" && patchedField.kind !== "scale"));\n    patchLog(log.id, {\n      fields,\n      ...(selectedHeatmapFieldBecameInvalid ? { heatmapFieldId: undefined } : {}),\n    });\n  };'''
if old not in s:
    raise SystemExit('patchField marker missing')
s=s.replace(old,new,1)
p.write_text(s)
print('cleared stale custom heatmap field refs')
