from pathlib import Path
p = Path('src/components/LogSheet.tsx')
s = p.read_text()
s = s.replace(
    'import { X, Plus, ChevronLeft, Check, Pencil } from "@/components/icons/BixboIcons";',
    'import { X, Plus, ChevronLeft, Check, Pencil, Trash2 } from "@/components/icons/BixboIcons";',
    1,
)
old = '''                          {savedEntries.map((entry, index) => (\n                            <button\n                              key={entry.id}\n                              type="button"\n                              onClick={() => setCustomEditEntry(entry)}\n                              className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-[10px] font-semibold ring-1 ring-border ${\n                                initialCustomEntry?.id === entry.id ? "bg-primary text-primary-foreground" : "bg-background text-foreground"\n                              }`}\n                            >\n                              <Pencil className="h-3 w-3" />\n                              {entry.time || `${t("Entry")} ${index + 1}`}\n                            </button>\n                          ))}'''
new = '''                          {savedEntries.map((entry, index) => (\n                            <div key={entry.id} className="inline-flex items-center gap-1">\n                              <button\n                                type="button"\n                                onClick={() => setCustomEditEntry(entry)}\n                                className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-[10px] font-semibold ring-1 ring-border ${\n                                  initialCustomEntry?.id === entry.id ? "bg-primary text-primary-foreground" : "bg-background text-foreground"\n                                }`}\n                              >\n                                <Pencil className="h-3 w-3" />\n                                {entry.time || `${t("Entry")} ${index + 1}`}\n                              </button>\n                              <button\n                                type="button"\n                                aria-label={`${t("Delete")} ${entry.time || `${t("Entry")} ${index + 1}`}`}\n                                onClick={() => {\n                                  if (!window.confirm(t("Delete this saved entry? Other entries and the selected day will stay unchanged."))) return;\n                                  update((current) => {\n                                    const day = current.dayLogs[date];\n                                    if (!day) return current;\n                                    const customLogs = { ...(day.customLogs ?? {}) };\n                                    const existing = customLogs[id] ?? [];\n                                    const nextEntries = existing.filter((saved) => saved.id !== entry.id);\n                                    if (nextEntries.length) customLogs[id] = nextEntries;\n                                    else delete customLogs[id];\n                                    return {\n                                      ...current,\n                                      dayLogs: {\n                                        ...current.dayLogs,\n                                        [date]: { ...day, customLogs },\n                                      },\n                                    };\n                                  });\n                                  if (customEditEntry?.id === entry.id) setCustomEditEntry(undefined);\n                                }}\n                                className="grid h-7 w-7 place-items-center rounded-full bg-background text-destructive ring-1 ring-border"\n                              >\n                                <Trash2 className="h-3.5 w-3.5" />\n                              </button>\n                            </div>\n                          ))}'''
if old not in s:
    raise SystemExit('saved entry buttons marker missing')
s = s.replace(old, new, 1)
p.write_text(s)
print('single custom log entry delete added')