from pathlib import Path
p=Path('src/routes/admin.tsx')
s=p.read_text()
needle='''function AdminPage() {\n  const { data, update, hydrated } = useBixbo();\n  const { t } = useI18n();\n'''
replacement='''const ADMIN_PIN_HASH = "dc4bc886825c446e6ae02d4d0c6a8787af0395079effcc3afc0f8bdc40cbd161";\n\nasync function sha256Hex(value: string) {\n  const bytes = new TextEncoder().encode(value);\n  const digest = await crypto.subtle.digest("SHA-256", bytes);\n  return Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2, "0")).join("");\n}\n\nfunction AdminPage() {\n  const { data, update, hydrated } = useBixbo();\n  const { t } = useI18n();\n  const [adminUnlocked, setAdminUnlocked] = useState(() => typeof window !== "undefined" && window.sessionStorage.getItem("bixbo-admin-unlocked") === "1");\n  const [adminPin, setAdminPin] = useState("");\n  const [pinError, setPinError] = useState(false);\n'''
if 'ADMIN_PIN_HASH' not in s:
    s=s.replace(needle,replacement)
marker='''  const surface = TAB_SURFACE[tab];\n\n  const features = useMemo('''
lock='''  const surface = TAB_SURFACE[tab];\n\n  if (!adminUnlocked) {\n    const unlock = async () => {\n      if ((await sha256Hex(adminPin)) === ADMIN_PIN_HASH) {\n        window.sessionStorage.setItem("bixbo-admin-unlocked", "1");\n        setPinError(false);\n        setAdminUnlocked(true);\n      } else {\n        setPinError(true);\n        setAdminPin("");\n      }\n    };\n    return (\n      <AppShell title={<Link to="/profile" className="flex items-center gap-2"><ArrowLeft className="h-5 w-5" />{t("Admin mode")}</Link>}>\n        <div className="mx-auto max-w-sm px-5 pt-10">\n          <section className="rounded-3xl bg-surface p-6 text-center shadow-sm ring-1 ring-border/80">\n            <div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-primary/10 text-2xl">🔒</div>\n            <p className="mt-4 font-serif text-xl font-bold">{t("Admin locked")}</p>\n            <p className="mt-1 text-xs text-muted-foreground">{t("Enter the admin PIN to continue.")}</p>\n            <input type="password" inputMode="numeric" maxLength={4} autoFocus value={adminPin} onChange={(event) => { setAdminPin(event.target.value.replace(/\\D/g, "").slice(0, 4)); setPinError(false); }} onKeyDown={(event) => { if (event.key === "Enter") void unlock(); }} className="mt-5 h-12 w-full rounded-2xl bg-tint px-4 text-center text-lg font-bold tracking-[0.45em] ring-1 ring-border focus:outline-none focus:ring-2 focus:ring-primary" aria-label={t("Admin PIN")} />\n            {pinError ? <p className="mt-2 text-xs font-semibold text-destructive">{t("Incorrect PIN")}</p> : null}\n            <button type="button" onClick={() => void unlock()} disabled={adminPin.length !== 4} className="mt-4 h-11 w-full rounded-2xl bg-primary text-sm font-semibold text-primary-foreground disabled:opacity-40">{t("Unlock admin")}</button>\n          </section>\n        </div>\n      </AppShell>\n    );\n  }\n\n  const features = useMemo('''
if 'Admin locked' not in s:
    s=s.replace(marker,lock)
p.write_text(s)
