from pathlib import Path

p=Path('src/lib/appRegistry.ts'); s=p.read_text()
s=s.replace('  /** Show the custom log icon on calendar days that contain entries. */\n  calendar?: boolean;\n  order: number;', '  /** Show the custom log icon on calendar days that contain entries. */\n  calendar?: boolean;\n  /** Show a shortcut in Quick Log. */\n  quickLog?: boolean;\n  /** Numeric/scale field exposed as a Heatmap metric. */\n  heatmapFieldId?: string;\n  order: number;')
p.write_text(s)

p=Path('src/components/CustomLogBuilder.tsx'); s=p.read_text()
s=s.replace('      calendar: true,\n      order:', '      calendar: true,\n      quickLog: false,\n      order:')
anchor='''            <div className="mt-3 flex items-center justify-between rounded-2xl bg-tint px-3 py-2 ring-1 ring-border/70">\n              <div><p className="text-xs font-semibold">{t("Show in Calendar")}</p><p className="text-[10px] text-muted-foreground">{t("Display this log's icon on days with saved entries.")}</p></div>\n              <button type="button" onClick={() => patchLog(log.id, { calendar: log.calendar === false })} className={`rounded-full px-3 py-1.5 text-[10px] font-semibold ${log.calendar === false ? "bg-background text-muted-foreground" : "bg-primary text-primary-foreground"}`}>{log.calendar === false ? t("Off") : t("On")}</button>\n            </div>\n'''
if 'Show in Quick Log' not in s:
    extra=anchor+'''\n            <div className="mt-2 flex items-center justify-between rounded-2xl bg-tint px-3 py-2 ring-1 ring-border/70">\n              <div><p className="text-xs font-semibold">{t("Show in Quick Log")}</p><p className="text-[10px] text-muted-foreground">{t("Add a shortcut that opens this custom log form.")}</p></div>\n              <button type="button" onClick={() => patchLog(log.id, { quickLog: !log.quickLog })} className={`rounded-full px-3 py-1.5 text-[10px] font-semibold ${log.quickLog ? "bg-primary text-primary-foreground" : "bg-background text-muted-foreground"}`}>{log.quickLog ? t("On") : t("Off")}</button>\n            </div>\n\n            {(() => {\n              const metricFields = fields.filter((field) => field.enabled !== false && (field.kind === "number" || field.kind === "scale"));\n              return (\n                <div className="mt-2 rounded-2xl bg-tint px-3 py-2 ring-1 ring-border/70">\n                  <p className="text-xs font-semibold">{t("Heatmap metric")}</p>\n                  <p className="text-[10px] text-muted-foreground">{t("Choose a numeric or scale field to expose in Insights Heatmap.")}</p>\n                  <select value={log.heatmapFieldId ?? ""} onChange={(event) => patchLog(log.id, { heatmapFieldId: event.target.value || undefined })} className="mt-2 h-9 w-full rounded-xl bg-background px-3 text-xs ring-1 ring-border">\n                    <option value="">{t("Off")}</option>\n                    {metricFields.map((field) => <option key={field.id} value={field.id}>{field.label}</option>)}\n                  </select>\n                </div>\n              );\n            })()}\n'''
    s=s.replace(anchor,extra)
p.write_text(s)

p=Path('src/components/QuickTags.tsx'); s=p.read_text()
s=s.replace('import { isRegistrySurfaceEnabled, type RegistryFeatureId } from "@/lib/appRegistry";', 'import { customLogDefinitions, isRegistrySurfaceEnabled, type RegistryFeatureId } from "@/lib/appRegistry";')
s=s.replace('type Cat = QuickTagCategory | "period" | "postpartum";', 'type Cat = QuickTagCategory | "period" | "postpartum" | "custom";')
s=s.replace('  popup?: "period" | "postpartum";\n  apply?:', '  popup?: "period" | "postpartum";\n  customLogId?: string;\n  apply?:')
s=s.replace('''  const registryAllowsQuickTag = (tag: Tag) => {\n    const id = registryIdForTag(tag);''','''  const registryAllowsQuickTag = (tag: Tag) => {\n    if (tag.cat === "custom") return true;\n    const id = registryIdForTag(tag);''')
needle='''  const allTags = [\n    ...(postpartumTag ? [postpartumTag] : []),'''
if 'const customLogTags:' not in s:
    s=s.replace(needle,'''  const customLogTags: Tag[] = customLogDefinitions(data)\n    .filter((log) => log.quickLog)\n    .map((log) => ({ key: `custom-log-${log.id}`, emoji: log.icon, label: log.label, cat: "custom", customLogId: log.id }));\n\n  const allTags = [\n    ...(postpartumTag ? [postpartumTag] : []),''')
s=s.replace('''      .map((tag) => customToTag(tag, data)),\n  ].filter(registryAllowsQuickTag);''','''      .map((tag) => customToTag(tag, data)),\n    ...customLogTags,\n  ].filter(registryAllowsQuickTag);''')
s=s.replace('''  const doTap = (tag: Tag) => {\n    if (tag.popup === "period") {''','''  const doTap = (tag: Tag) => {\n    if (tag.customLogId) {\n      onLongPress(`custom:${tag.customLogId}`);\n      return;\n    }\n    if (tag.popup === "period") {''')
p.write_text(s)

p=Path('src/routes/insights.tsx'); s=p.read_text()
s=s.replace('import { getRegistryFeature, isRegistrySurfaceEnabled } from "@/lib/appRegistry";', 'import { customLogDefinitions, getRegistryFeature, isRegistrySurfaceEnabled } from "@/lib/appRegistry";')
s=s.replace('type HeatmapMetric = "pain" | "period" | "bowel" | "panic" | "tetany" | "hotFlashes" | "sleep";', 'type HeatmapMetric = "pain" | "period" | "bowel" | "panic" | "tetany" | "hotFlashes" | "sleep" | `custom:${string}:${string}`;')
old='''  const availableHeatmapOptions = useMemo(\n    () => HEATMAP_OPTIONS\n      .filter((option) => isRegistrySurfaceEnabled(data, option.id, "heatmap"))\n      .map((option) => ({ ...option, label: getRegistryFeature(data, option.id).label })),\n    [data],\n  );'''
new='''  const availableHeatmapOptions = useMemo(() => {\n    const builtins = HEATMAP_OPTIONS\n      .filter((option) => isRegistrySurfaceEnabled(data, option.id, "heatmap"))\n      .map((option) => ({ ...option, label: getRegistryFeature(data, option.id).label }));\n    const customs = customLogDefinitions(data).flatMap((log) => {\n      if (!log.heatmapFieldId) return [];\n      const field = log.fields.find((item) => item.id === log.heatmapFieldId && item.enabled !== false && (item.kind === "number" || item.kind === "scale"));\n      if (!field) return [];\n      return [{ id: `custom:${log.id}:${field.id}` as HeatmapMetric, label: `${log.label} · ${field.label}` }];\n    });\n    return [...builtins, ...customs];\n  }, [data]);'''
s=s.replace(old,new)
needle='''      const log = data.dayLogs[key];\n      if (!log) return null;\n\n      if (selectedMetric === "pain") {'''
custom='''      const log = data.dayLogs[key];\n      if (!log) return null;\n\n      if (selectedMetric.startsWith("custom:")) {\n        const [, logId, fieldId] = selectedMetric.split(":");\n        const definition = customLogDefinitions(data).find((item) => item.id === logId);\n        const field = definition?.fields.find((item) => item.id === fieldId);\n        const entries = log.customLogs?.[logId] ?? [];\n        const values = entries.map((entry) => Number(entry.values[fieldId])).filter((value) => Number.isFinite(value));\n        if (!definition || !field || !values.length) return null;\n        const value = values.reduce((sum, item) => sum + item, 0) / values.length;\n        const min = field.scale?.min ?? Math.min(...values, 0);\n        const max = field.scale?.max ?? Math.max(...values, 10);\n        const span = Math.max(0.0001, max - min);\n        const normalized = Math.max(0, Math.min(10, ((value - min) / span) * 10));\n        return { color: vividPainChartColor(normalized), tooltipColor: vividPainChartColor(normalized), value: Number.isInteger(value) ? String(value) : value.toFixed(1), popupValue: `${field.label} · ${Number.isInteger(value) ? value : value.toFixed(1)}`, description: definition.label, entryCount: values.length };\n      }\n\n      if (selectedMetric === "pain") {'''
s=s.replace(needle,custom)
s=s.replace('const activeMetricLabel = HEATMAP_OPTIONS.find((option) => option.id === metric)?.label ?? "Heatmap";', 'const activeMetricLabel = availableHeatmapOptions.find((option) => option.id === metric)?.label ?? "Heatmap";')
s=s.replace('''  const legend = (() => {\n    if (metric === "period") {''','''  const legend = (() => {\n    if (metric.startsWith("custom:")) {\n      return [["Low", vividPainChartColor(0)], ["Mild", vividPainChartColor(2.5)], ["Moderate", vividPainChartColor(5)], ["High", vividPainChartColor(7.5)], ["Severe", vividPainChartColor(10)]] as const;\n    }\n    if (metric === "period") {''')
# dependency for datumFor: replace nearest exact dependency after function
s=s.replace('''    [data.dayLogs],\n  );\n\n  const compactDays''','''    [data],\n  );\n\n  const compactDays''')
p.write_text(s)
