import { Link, useRouterState, useNavigate } from "@tanstack/react-router";
import { type ComponentType } from "react";
import { useI18n } from "@/hooks/useI18n";
import type { IconProps } from "@/components/icons/BixboExtraIcons";
import { BottomNavHomeIcon, BottomNavOverviewIcon, BottomNavCoupleIcon, BottomNavNoteIcon, BottomNavLogIcon } from "@/components/icons/BottomNavReferenceIcons";
import { BIXBO_NAVIGATION, resolvedNavigation, type NavigationItemId } from "@/lib/navigationRegistry";

const ICONS: Record<NavigationItemId, ComponentType<IconProps>> = { home: BottomNavHomeIcon, overview: BottomNavOverviewIcon, log: BottomNavLogIcon, couple: BottomNavCoupleIcon, notes: BottomNavNoteIcon, healthProfile: BottomNavHomeIcon };
const NAV_IMAGE_SRC: Partial<Record<NavigationItemId, string>> = { home: "/nav-assets/nav-home-user.webp?v=exact-4", overview: "/nav-assets/nav-overview-approved.webp?v=exact-3", log: "/nav-assets/nav-log-user.svg?v=user-plus-1", couple: "/nav-assets/nav-couple-user.webp?v=exact-4", notes: "/nav-assets/nav-note-approved.webp?v=exact-3" };

function NavArtwork({ id, size, className }: { id: NavigationItemId; size: number; className?: string }) { const Icon = ICONS[id]; const imageSrc = NAV_IMAGE_SRC[id]; if (imageSrc) return <img src={imageSrc} alt="" aria-hidden="true" draggable={false} width={size} height={size} className={className} style={{ objectFit: "contain" }} onError={(event) => { event.currentTarget.style.display = "none"; const fallback = event.currentTarget.parentElement?.querySelector<SVGElement>("svg[data-nav-fallback]"); if (fallback) fallback.style.display = ""; }} />; return <Icon size={size} className={className} />; }
function NavArtworkSafe({ id, size, className }: { id: NavigationItemId; size: number; className?: string }) { const Icon = ICONS[id]; return <span className="relative inline-flex shrink-0 items-center justify-center" style={{ width: size, height: size }}><NavArtwork id={id} size={size} className={className} /><Icon data-nav-fallback size={size} className={className} style={{ display: "none" }} /></span>; }

export function BottomNav() {
  const pathname = useRouterState({ select: (s) => s.location.pathname }); const navigate = useNavigate(); const { t } = useI18n(); const items = resolvedNavigation("mobile");
  const openLog = () => { if (pathname === "/") window.dispatchEvent(new CustomEvent("bixbo:open-log")); else navigate({ to: "/", search: { log: 1 } as never }); };
  return <nav aria-label="Primary navigation" className="fixed inset-x-0 bottom-0 z-40 w-full border-t border-border/55 bg-[#FBF7F3]/96 pb-[max(8px,env(safe-area-inset-bottom))] backdrop-blur-xl supports-[backdrop-filter]:bg-[#FBF7F3]/92 lg:hidden dark:border-border/65 dark:bg-background/96 dark:supports-[backdrop-filter]:bg-background/92" style={{ boxShadow: "0 -8px 22px -17px rgba(45,58,26,.28), inset 0 1px 0 color-mix(in srgb, var(--border) 35%, transparent)" }}><ul className="mx-auto flex min-h-[88px] w-full max-w-[430px] items-end justify-around gap-0 px-2 pb-1.5 pt-1 sm:px-4 landscape:min-h-[76px] landscape:py-1">{items.map((item) => { const label = item.label ?? BIXBO_NAVIGATION.find((candidate) => candidate.id === item.id)?.label ?? item.id; if (item.action === "log") return <li key={item.id} className="flex min-w-0 flex-1 justify-center"><button type="button" onClick={openLog} className="flex min-h-[72px] w-full flex-col items-center justify-end gap-0 px-1 pb-0.5 text-[11px] font-semibold text-[#3f4e27] transition-transform focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring active:scale-[0.97] dark:text-foreground landscape:min-h-[62px]" aria-label={t(label)}><NavArtworkSafe id={item.id} size={64} className="-mb-1 h-[64px] w-[64px] shrink-0 object-contain drop-shadow-[0_7px_8px_rgba(52,67,30,0.20)] landscape:h-[54px] landscape:w-[54px]" /><span className="max-w-full truncate text-center leading-none">{t(label)}</span></button></li>; const to = item.to ?? "/"; const active = item.id === "overview" ? pathname.startsWith("/insights") || pathname.startsWith("/patterns") : to === "/" ? pathname === "/" : pathname.startsWith(to); return <li key={item.id} className="flex min-w-0 flex-1 justify-center"><Link to={to as never} aria-current={active ? "page" : undefined} className={`relative flex min-h-[72px] w-full flex-col items-center justify-end gap-0 px-1 pb-0.5 text-[11px] font-semibold transition-transform focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring active:scale-[0.97] landscape:min-h-[62px] ${active ? "text-[#34431f] dark:text-foreground" : "text-[#45542b]/95 hover:text-[#34411f] dark:text-muted-foreground dark:hover:text-foreground"}`}><NavArtworkSafe id={item.id} size={54} className={`mb-0 h-[54px] w-[54px] shrink-0 object-contain drop-shadow-[0_6px_7px_rgba(52,67,30,0.18)] transition-transform landscape:h-[46px] landscape:w-[46px] ${active ? "scale-[1.04]" : ""}`} /><span className="max-w-full truncate text-center leading-none">{t(label)}</span>{active ? <span aria-hidden="true" className="absolute bottom-[-3px] h-1 w-5 rounded-full bg-current opacity-70" /> : null}</Link></li>; })}</ul></nav>;
}
