from pathlib import Path

log_path = Path('src/components/LogSheet.tsx')
s = log_path.read_text()
old = '''      <Field label="Time" schemaFieldId="time">\n        <Input type="time" value={time} onChange={(e) => setTime(e.target.value)} />\n      </Field>\n      <Field label="Type" schemaFieldId="types">\n        <CustomChipList\n          base={TETANY_TYPES}\n          custom={data.custom.tetanyTypes}\n          descriptions={TETANY_TYPE_DESC}\n          onAddCustom={(v) => addC("tetanyTypes", v)}\n          onRemoveCustom={(v) => {\n            rmC("tetanyTypes", v);\n            setTypes((a) => a.filter((x) => x !== v));\n          }}\n          onRenameCustom={(o, n) => {\n            rnC("tetanyTypes", o, n);\n            setTypes((a) => a.map((x) => (x === o ? n : x)));\n          }}\n          selected={types}\n          onToggle={(v) => setTypes((a) => toggleIn(a, v))}\n        />\n      </Field>\n      <Field label="Location" schemaFieldId="location">\n        <CustomChipList\n          base={TETANY_LOCATIONS_DEFAULT}\n          custom={data.custom.tetanyLocations}\n          onAddCustom={(v) => addC("tetanyLocations", v)}\n          onRemoveCustom={(v) => {\n            rmC("tetanyLocations", v);\n            setLoc((a) => a.filter((x) => x !== v));\n          }}\n          onRenameCustom={(o, n) => {\n            rnC("tetanyLocations", o, n);\n            setLoc((a) => a.map((x) => (x === o ? n : x)));\n          }}\n          selected={loc}\n          onToggle={(v) => setLoc((a) => toggleIn(a, v))}\n        />\n      </Field>\n      <Field label={`Intensity ${intensity}/5`} schemaFieldId="intensity">\n        <IntensityScale\n          value={intensity}\n          onChange={setIntensity}\n          max={5}\n          descriptions={getScaleDesc(data, "tetany")}\n          legendTitle="Tetany intensity scale" schemaFieldId="intensity"\n        />\n      </Field>\n      <DurationField minutes={minutes} setMinutes={setMinutes} ongoing={ongoing} setOngoing={setOngoing} schemaFieldId="duration" />'''
new = '''      <Field label="Time" schemaFieldId="time">\n        <Input type="time" value={time} onChange={(e) => setTime(e.target.value)} />\n      </Field>\n      <DurationField minutes={minutes} setMinutes={setMinutes} ongoing={ongoing} setOngoing={setOngoing} schemaFieldId="duration" />\n      <Field label={`Intensity ${intensity}/5`} schemaFieldId="intensity">\n        <IntensityScale\n          value={intensity}\n          onChange={setIntensity}\n          max={5}\n          descriptions={getScaleDesc(data, "tetany")}\n          legendTitle="Tetany intensity scale" schemaFieldId="intensity"\n        />\n      </Field>\n      <Field label="Type" schemaFieldId="types">\n        <CustomChipList\n          base={TETANY_TYPES}\n          custom={data.custom.tetanyTypes}\n          descriptions={TETANY_TYPE_DESC}\n          onAddCustom={(v) => addC("tetanyTypes", v)}\n          onRemoveCustom={(v) => {\n            rmC("tetanyTypes", v);\n            setTypes((a) => a.filter((x) => x !== v));\n          }}\n          onRenameCustom={(o, n) => {\n            rnC("tetanyTypes", o, n);\n            setTypes((a) => a.map((x) => (x === o ? n : x)));\n          }}\n          selected={types}\n          onToggle={(v) => setTypes((a) => toggleIn(a, v))}\n        />\n      </Field>\n      <Field label="Location" schemaFieldId="location">\n        <CustomChipList\n          base={TETANY_LOCATIONS_DEFAULT}\n          custom={data.custom.tetanyLocations}\n          onAddCustom={(v) => addC("tetanyLocations", v)}\n          onRemoveCustom={(v) => {\n            rmC("tetanyLocations", v);\n            setLoc((a) => a.filter((x) => x !== v));\n          }}\n          onRenameCustom={(o, n) => {\n            rnC("tetanyLocations", o, n);\n            setLoc((a) => a.map((x) => (x === o ? n : x)));\n          }}\n          selected={loc}\n          onToggle={(v) => setLoc((a) => toggleIn(a, v))}\n        />\n      </Field>'''
if old not in s:
    raise SystemExit('Tetany field-order block not found')
s = s.replace(old, new, 1)
log_path.write_text(s)

overview_path = Path('src/components/home/DayOverview.tsx')
s = overview_path.read_text()
food_old = '''      {log?.food?.length ? (\n        <Card title="Food" icon="🍽️">\n          <ul className="space-y-2">'''
food_new = '''      {log?.food?.length ? (\n        <Card title="Food" icon="🍽️">\n          <ul className="space-y-1.5">'''
if food_old not in s:
    raise SystemExit('Food section start not found')
s = s.replace(food_old, food_new, 1)
food_start = s.index('      {log?.food?.length ? (')
food_end = s.index('      {log?.bowel?.length ? (', food_start)
food = s[food_start:food_end]
food = food.replace('border-t border-border/60 pt-2', 'border-t border-border/60 pt-1.5')
food = food.replace('className="my-1.5 border-t border-border/60"', 'className="my-1 border-t border-border/60"')
food = food.replace('className="mt-1 text-xs leading-snug', 'className="mt-0.5 text-xs leading-snug')
food = food.replace('className="mt-1 whitespace-pre-line text-xs leading-snug"', 'className="mt-0.5 whitespace-pre-line text-xs leading-snug"')
food = food.replace('className="mt-0.5 text-[10px] text-primary"', 'className="mt-0 text-[10px] text-primary"')
s = s[:food_start] + food + s[food_end:]

sleep_old = '''      {log?.workout?.length ? ('''
# Replace only the Temp/Sleep/Weight card later in the file.
old_card = '''      ) : null}      {(log?.temperature != null || log?.weight != null || log?.sleepHours != null || log?.sleepQuality) && (\n        <Card title="Temp / Sleep / Weight" icon="🌡️">\n          <button onClick={() => onEdit?.("temp", undefined)} className="w-full text-left">\n            {log?.temperature != null && <p className="text-sm">{t("Temperature")}: {log.temperature}°C</p>}\n            {log?.weight != null && <p className="text-sm">{t("Weight")}: {log.weight} kg</p>}\n            {log?.sleepHours != null && (\n              <p className="text-sm">\n                {t("Sleep")}: {log.sleepHours} h <IcoText text={asArr(log.sleepQuality).join(", ")} size={14} />\n              </p>\n            )}\n            {asArr(log?.sleepQuality).length > 0 && log?.sleepHours == null && (\n              <p className="text-sm">\n                {t("Sleep quality")}: <IcoText text={asArr(log.sleepQuality).map(t).join(", ")} size={14} />\n              </p>\n            )}\n            <p className="mt-1 text-[10px] text-primary">{t("Tap to edit")}</p>\n          </button>\n        </Card>\n      )}'''
new_card = '''      ) : null}\n\n      {(log?.temperature != null || log?.weight != null || log?.sleepHours != null || log?.sleepQuality) && (\n        <Card title="Temp / Sleep / Weight" icon="🌡️">\n          <button onClick={() => onEdit?.("temp", undefined)} className="w-full text-left">\n            <div className="my-1 border-t border-border/60" />\n            {log?.temperature != null && (\n              <p className="text-xs leading-snug text-muted-foreground">\n                <span className="font-semibold text-foreground">{t("Temperature")}:</span> {log.temperature}°C\n              </p>\n            )}\n            {log?.weight != null && (\n              <p className={`${log?.temperature != null ? "mt-0.5 " : ""}text-xs leading-snug text-muted-foreground`}>\n                <span className="font-semibold text-foreground">{t("Weight")}:</span> {log.weight} kg\n              </p>\n            )}\n            {log?.sleepHours != null && (\n              <p className={`${log?.temperature != null || log?.weight != null ? "mt-0.5 " : ""}text-xs leading-snug text-muted-foreground`}>\n                <span className="font-semibold text-foreground">{t("Sleep")}:</span> {log.sleepHours} h\n                {asArr(log.sleepQuality).length ? <> · <IcoText text={asArr(log.sleepQuality).map(t).join(", ")} size={13} /></> : null}\n              </p>\n            )}\n            {asArr(log?.sleepQuality).length > 0 && log?.sleepHours == null && (\n              <p className={`${log?.temperature != null || log?.weight != null ? "mt-0.5 " : ""}text-xs leading-snug text-muted-foreground`}>\n                <span className="font-semibold text-foreground">{t("Sleep quality")}:</span>{" "}\n                <IcoText text={asArr(log.sleepQuality).map(t).join(", ")} size={13} />\n              </p>\n            )}\n            <p className="mt-0.5 text-[10px] text-primary">{t("Tap to edit")}</p>\n          </button>\n        </Card>\n      )}'''
if old_card not in s:
    raise SystemExit('Temp/Sleep/Weight card block not found')
s = s.replace(old_card, new_card, 1)
overview_path.write_text(s)
