from pathlib import Path

p = Path('src/routes/insights.tsx')
s = p.read_text()

s = s.replace(
'''  avgDayPain,\n} from "@/lib/storage";''',
'''  avgDayPain,\n  medScheduleItems,\n} from "@/lib/storage";''',
1,
)

old = '''  const perDay = useMemo(\n    () =>\n      days.map((date) => {\n        const missed: { medName: string; time: string; key: string }[] = [];\n        const takenList: { medName: string; time: string; key: string }[] = [];\n        let expected = 0;\n        let taken = 0;\n\n        scheduled.forEach((med) => {\n          med.times.forEach((time) => {\n            const key = `${med.id}@${time}`;\n            const isTaken = !!data.medLog[date]?.[key];\n\n            if (!isDoseEligibleNow(date, time, isTaken, adherenceNow)) return;\n\n            expected += 1;\n\n            if (isTaken) {\n              taken += 1;\n              takenList.push({ medName: med.name, time, key });\n            } else {\n              missed.push({ medName: med.name, time, key });\n            }\n          });\n        });\n\n        return {\n          date,\n          expected,\n          taken,\n          missed,\n          takenList,\n          pct: expected ? Math.round((taken / expected) * 100) : null,\n        };\n      }),\n    [\n      data.medLog,\n      days,\n      scheduled,\n      adherenceNow.getFullYear(),\n      adherenceNow.getMonth(),\n      adherenceNow.getDate(),\n      adherenceNow.getHours(),\n      adherenceNow.getMinutes(),\n    ],\n  );'''
new = '''  const perDay = useMemo(\n    () =>\n      days.map((date) => {\n        const missed: { medName: string; time: string; key: string; item: string }[] = [];\n        const takenList: { medName: string; time: string; key: string; item: string }[] = [];\n        let expected = 0;\n        let taken = 0;\n\n        scheduled.forEach((med) => {\n          const scheduleItems = medScheduleItems(med);\n          med.times.forEach((time) => {\n            const key = `${med.id}@${time}`;\n            const isTaken = !!data.medLog[date]?.[key];\n\n            if (!isDoseEligibleNow(date, time, isTaken, adherenceNow)) return;\n\n            expected += scheduleItems.length;\n            const storedItems = data.medLogItems?.[date]?.[key];\n            const selectedItems = storedItems ?? (isTaken ? scheduleItems : []);\n            const selectedSet = new Set(selectedItems.filter((item) => scheduleItems.includes(item)));\n\n            scheduleItems.forEach((item) => {\n              if (selectedSet.has(item)) {\n                taken += 1;\n                takenList.push({ medName: item, time, key, item });\n              } else {\n                missed.push({ medName: item, time, key, item });\n              }\n            });\n          });\n        });\n\n        return {\n          date,\n          expected,\n          taken,\n          missed,\n          takenList,\n          pct: expected ? Math.round((taken / expected) * 100) : null,\n        };\n      }),\n    [\n      data.medLog,\n      data.medLogItems,\n      days,\n      scheduled,\n      adherenceNow.getFullYear(),\n      adherenceNow.getMonth(),\n      adherenceNow.getDate(),\n      adherenceNow.getHours(),\n      adherenceNow.getMinutes(),\n    ],\n  );'''
if old not in s:
    raise SystemExit('perDay block not found')
s = s.replace(old, new, 1)

old = '''  const perMed = useMemo(\n    () =>\n      scheduled\n        .flatMap((med) =>\n          med.times.map((time) => {\n            let expected = 0;\n            let taken = 0;\n\n            days.forEach((date) => {\n              const key = `${med.id}@${time}`;\n              const isTaken = !!data.medLog[date]?.[key];\n\n              if (!isDoseEligibleNow(date, time, isTaken, adherenceNow)) return;\n\n              expected += 1;\n              if (isTaken) taken += 1;\n            });\n\n            const pct = expected ? Math.round((taken / expected) * 100) : null;\n\n            return {\n              id: `${med.id}@${time}`,\n              name: med.name,\n              dose: med.dose,\n              time,\n              taken,\n              expected,\n              pct,\n            };\n          }),\n        )\n        .filter((entry) => entry.expected > 0)\n        .sort((a, b) => (a.pct ?? 0) - (b.pct ?? 0)),\n    [\n      data.medLog,\n      days,\n      scheduled,\n      adherenceNow.getFullYear(),\n      adherenceNow.getMonth(),\n      adherenceNow.getDate(),\n      adherenceNow.getHours(),\n      adherenceNow.getMinutes(),\n    ],\n  );'''
new = '''  const perMed = useMemo(\n    () =>\n      scheduled\n        .flatMap((med) =>\n          med.times.flatMap((time) =>\n            medScheduleItems(med).map((item) => {\n              let expected = 0;\n              let taken = 0;\n\n              days.forEach((date) => {\n                const key = `${med.id}@${time}`;\n                const isTaken = !!data.medLog[date]?.[key];\n\n                if (!isDoseEligibleNow(date, time, isTaken, adherenceNow)) return;\n\n                expected += 1;\n                const allItems = medScheduleItems(med);\n                const storedItems = data.medLogItems?.[date]?.[key];\n                const selectedItems = storedItems ?? (isTaken ? allItems : []);\n                if (selectedItems.includes(item)) taken += 1;\n              });\n\n              const pct = expected ? Math.round((taken / expected) * 100) : null;\n\n              return {\n                id: `${med.id}@${time}@${item}`,\n                name: item,\n                dose: med.dose,\n                time,\n                taken,\n                expected,\n                pct,\n              };\n            }),\n          ),\n        )\n        .filter((entry) => entry.expected > 0)\n        .sort((a, b) => (a.pct ?? 0) - (b.pct ?? 0)),\n    [\n      data.medLog,\n      data.medLogItems,\n      days,\n      scheduled,\n      adherenceNow.getFullYear(),\n      adherenceNow.getMonth(),\n      adherenceNow.getDate(),\n      adherenceNow.getHours(),\n      adherenceNow.getMinutes(),\n    ],\n  );'''
if old not in s:
    raise SystemExit('perMed block not found')
s = s.replace(old, new, 1)

old = '''  const toggleDose = (dayKey: string, medKey: string) =>\n    update((current) => {\n      const day = { ...(current.medLog[dayKey] ?? {}) };\n\n      if (day[medKey]) delete day[medKey];\n      else day[medKey] = true;\n\n      return {\n        ...current,\n        medLog: {\n          ...current.medLog,\n          [dayKey]: day,\n        },\n      };\n    });'''
new = '''  const toggleDose = (dayKey: string, medKey: string, item?: string) =>\n    update((current) => {\n      const day = { ...(current.medLog[dayKey] ?? {}) };\n      const dayItems = { ...(current.medLogItems?.[dayKey] ?? {}) };\n\n      if (!item) {\n        if (day[medKey]) {\n          delete day[medKey];\n          delete dayItems[medKey];\n        } else {\n          day[medKey] = true;\n        }\n      } else {\n        const [medId, time] = medKey.split("@");\n        const med = current.meds.find((entry) => entry.id === medId);\n        const allItems = med ? medScheduleItems(med) : [item];\n        const existing = dayItems[medKey] ?? (day[medKey] ? allItems : []);\n        const next = new Set(existing.filter((name) => allItems.includes(name)));\n\n        if (next.has(item)) next.delete(item);\n        else next.add(item);\n\n        const selected = allItems.filter((name) => next.has(name));\n        if (selected.length) {\n          day[medKey] = true;\n          dayItems[medKey] = selected;\n        } else {\n          delete day[medKey];\n          delete dayItems[medKey];\n        }\n      }\n\n      return {\n        ...current,\n        medLog: {\n          ...current.medLog,\n          [dayKey]: day,\n        },\n        medLogItems: {\n          ...(current.medLogItems ?? {}),\n          [dayKey]: dayItems,\n        },\n      };\n    });'''
if old not in s:
    raise SystemExit('toggleDose block not found')
s = s.replace(old, new, 1)

s = s.replace('''onClick={() => toggleDose(day.date, med.key)}''', '''onClick={() => toggleDose(day.date, med.key, med.item)}''')

p.write_text(s)
