from pathlib import Path

def repl(path, old, new):
    p=Path(path); s=p.read_text()
    if old not in s:
        raise SystemExit(f'missing in {path}: {old[:120]!r}')
    p.write_text(s.replace(old,new,1))

# NOTES: replace fragile contentEditable + hidden bridge with a native textarea.
p='src/routes/notes-editor.tsx'
s=Path(p).read_text()
s=s.replace('  const editorRef = useRef<HTMLDivElement | null>(null);\n  const keyboardBridgeRef = useRef<HTMLTextAreaElement | null>(null);\n','  const editorRef = useRef<HTMLTextAreaElement | null>(null);\n')
s=s.replace('  const contentRef = useRef(initialContentRef.current);\n','  const contentRef = useRef(initialContentRef.current.replace(/<br\\s*\\/?>(?!$)/gi, "\\n").replace(/<\\/div>/gi, "\\n").replace(/<[^>]+>/g, ""));\n  const [bodyText, setBodyText] = useState(contentRef.current);\n')
start=s.index('  const exec = (command: "bold" | "highlight") => {')
end=s.index('\n\n  return (', start)
new_funcs='''  const exec = (command: "bold" | "highlight") => {\n    const editor = editorRef.current;\n    if (!editor) return;\n    const start = editor.selectionStart ?? 0;\n    const end = editor.selectionEnd ?? start;\n    const selected = bodyText.slice(start, end);\n    const left = command === "bold" ? "**" : "==";\n    const right = left;\n    const next = `${bodyText.slice(0, start)}${left}${selected}${right}${bodyText.slice(end)}`;\n    setBodyText(next);\n    contentRef.current = next;\n    setTick((value) => value + 1);\n    requestAnimationFrame(() => {\n      editor.focus();\n      const caret = selected ? end + left.length * 2 : start + left.length;\n      editor.setSelectionRange(caret, caret);\n    });\n  };\n\n  const onInput = (value: string) => {\n    setBodyText(value);\n    contentRef.current = value;\n    setTick((current) => current + 1);\n  };'''
s=s[:start]+new_funcs+s[end:]
old='''        <div className="rounded-3xl p-4 ring-1 ring-border/70" style={{ background: NOTE_COLORS[color] }}>\n          <textarea\n            ref={keyboardBridgeRef}\n            tabIndex={0}\n            inputMode="text"\n            autoCapitalize="sentences"\n            className="fixed left-0 top-0 h-px w-px opacity-0 text-base"\n            aria-label={t("Note keyboard input")}\n          />\n          <div\n            key={`${note.id}:${editorReady ? "ready" : "boot"}`}\n            ref={editorRef}\n            contentEditable\n            suppressContentEditableWarning\n            role="textbox"\n            aria-multiline="true"\n            tabIndex={0}\n            inputMode="text"\n            spellCheck\n            autoCapitalize="sentences"\n            autoCorrect="on"\n            data-bixbo-note-editor\n            dangerouslySetInnerHTML={{ __html: initialContentRef.current }}\n            onPointerDown={(event) => {\n              if (event.pointerType === "touch") primeIOSKeyboard();\n            }}\n            onInput={onInput}\n            onBlur={onInput}\n            className="relative z-10 min-h-[40dvh] touch-manipulation select-text text-base leading-relaxed whitespace-pre-wrap outline-none empty:before:pointer-events-none empty:before:text-muted-foreground empty:before:content-[attr(data-placeholder)]"\n            style={{ WebkitUserSelect: "text", userSelect: "text" }}\n            data-placeholder={t("Start writing…")}\n          />\n        </div>'''
new='''        <div className="rounded-3xl p-4 ring-1 ring-border/70" style={{ background: NOTE_COLORS[color] }}>\n          <textarea\n            key={`${note.id}:${editorReady ? "ready" : "boot"}`}\n            ref={editorRef}\n            value={bodyText}\n            onChange={(event) => onInput(event.target.value)}\n            onBlur={(event) => onInput(event.target.value)}\n            rows={14}\n            inputMode="text"\n            spellCheck\n            autoCapitalize="sentences"\n            autoCorrect="on"\n            data-bixbo-note-editor\n            placeholder={t("Start writing…")}\n            className="block min-h-[40dvh] w-full resize-none bg-transparent text-base leading-relaxed text-foreground outline-none placeholder:text-muted-foreground"\n          />\n        </div>'''
if old not in s: raise SystemExit('notes editor block missing')
s=s.replace(old,new,1)
# save plain text instead of HTML sanitizer; safe as React renders it as text later
s=s.replace('content: sanitizeNoteHtml(contentRef.current),','content: contentRef.current,')
Path(p).write_text(s)

# PDF: use html2canvas + jsPDF to generate a real downloadable PDF, plus safe-area toolbar.
p='src/routes/report.tsx'
s=Path(p).read_text()
s=s.replace('import { useMemo, useState } from "react";','import { useMemo, useRef, useState } from "react";')
s=s.replace('  const [printPreviewOpen, setPrintPreviewOpen] = useState(false);','''  const [printPreviewOpen, setPrintPreviewOpen] = useState(false);\n  const [pdfBusy, setPdfBusy] = useState(false);\n  const printPreviewRef = useRef<HTMLDivElement | null>(null);\n\n  const savePdf = async () => {\n    const page = printPreviewRef.current?.querySelector<HTMLElement>(".pdf-page");\n    if (!page || pdfBusy) return;\n    setPdfBusy(true);\n    try {\n      const [{ default: html2canvas }, { jsPDF }] = await Promise.all([import("html2canvas"), import("jspdf")]);\n      const canvas = await html2canvas(page, { scale: 2, backgroundColor: "#ffffff", useCORS: true, logging: false });\n      const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4", compress: true });\n      const pageWidth = pdf.internal.pageSize.getWidth();\n      const pageHeight = pdf.internal.pageSize.getHeight();\n      const imgWidth = pageWidth;\n      const imgHeight = canvas.height * imgWidth / canvas.width;\n      const image = canvas.toDataURL("image/jpeg", 0.92);\n      let y = 0;\n      let remaining = imgHeight;\n      pdf.addImage(image, "JPEG", 0, y, imgWidth, imgHeight, undefined, "FAST");\n      remaining -= pageHeight;\n      while (remaining > 0) {\n        y -= pageHeight;\n        pdf.addPage();\n        pdf.addImage(image, "JPEG", 0, y, imgWidth, imgHeight, undefined, "FAST");\n        remaining -= pageHeight;\n      }\n      pdf.save(`BIXBO-${month}-${style}.pdf`);\n    } finally {\n      setPdfBusy(false);\n    }\n  };''')
s=s.replace('<div className="pdf-print-preview fixed inset-0 z-[10050] overflow-y-auto bg-background p-3 pb-24">','<div ref={printPreviewRef} className="pdf-print-preview fixed inset-0 z-[10050] overflow-y-auto bg-background px-3 pb-24 pt-[calc(env(safe-area-inset-top)+.75rem)]">')
s=s.replace('className="pdf-preview-toolbar sticky top-0 z-10 mx-auto mb-3 flex max-w-[820px] items-center gap-2 rounded-2xl bg-background/95 p-2 shadow-lg ring-1 ring-border backdrop-blur"','className="pdf-preview-toolbar sticky top-[env(safe-area-inset-top)] z-10 mx-auto mb-3 flex max-w-[820px] items-center gap-2 rounded-2xl bg-background/95 p-2 shadow-lg ring-1 ring-border backdrop-blur"')
s=s.replace('<button type="button" onClick={() => window.print()} className="h-10 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground">{t("Print / Save PDF")}</button>','<button type="button" onClick={savePdf} disabled={pdfBusy} className="h-10 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-60">{pdfBusy ? t("Creating PDF…") : t("Save PDF")}</button>')
Path(p).write_text(s)
print('patched notes and pdf')
