from pathlib import Path
p=Path('src/components/home/DayOverview.tsx')
s=p.read_text()
old='''          <Card title="Blueberry" icon="🫐">\n            <button onClick={() => onEdit?.("period", undefined)} className="w-full text-left">\n              {(log?.periodInfo?.level || log?.period) && (\n                <p className="text-sm">{t("Flow")}: {flowLabel(log?.periodInfo?.level ?? log?.period)}</p>\n              )}\n              {log?.periodInfo?.cramps != null && (\n                <p className="text-xs" style={{ color: painColor(log.periodInfo.cramps) }}>\n                  {t("Cramp pain")}:{" "}\n                  <span className="font-semibold">\n                    {Number.isInteger(log.periodInfo.cramps) ? log.periodInfo.cramps : log.periodInfo.cramps.toFixed(1)}\n                    /10\n                  </span>{" "}\n                  — {t(PAIN_DESCRIPTIONS[Math.round(log.periodInfo.cramps)])}\n                </p>\n              )}\n              {log?.periodInfo?.discharge && (\n                <p className="text-xs text-muted-foreground">\n                  {t("Discharge")}: {t(log.periodInfo.discharge)}\n                  {log.periodInfo.dischargeNote ? ` — ${log.periodInfo.dischargeNote}` : ""}\n                </p>\n              )}\n              {log?.periodInfo?.note && <p className="mt-1 text-sm whitespace-pre-line">"{log.periodInfo.note}"</p>}\n              <p className="mt-1 text-[10px] text-primary">{t("Tap to edit")}</p>\n            </button>\n          </Card>'''
new='''          <Card title="Blueberry" icon="🫐">\n            <button onClick={() => onEdit?.("period", undefined)} className="w-full text-left">\n              <div className="my-2 border-t border-border/60" />\n              {(log?.periodInfo?.level || log?.period) && (\n                <p className="text-xs leading-relaxed text-muted-foreground">\n                  <span className="font-semibold text-foreground">{t("Flow")}:</span>{" "}\n                  {flowLabel(log?.periodInfo?.level ?? log?.period)}\n                </p>\n              )}\n              {log?.periodInfo?.cramps != null && (\n                <p className="mt-2 text-xs leading-relaxed text-muted-foreground">\n                  <span className="font-semibold text-foreground">{t("Cramp pain")}:</span>{" "}\n                  <span style={{ color: painColor(log.periodInfo.cramps) }}>\n                    {Number.isInteger(log.periodInfo.cramps) ? log.periodInfo.cramps : log.periodInfo.cramps.toFixed(1)}/10\n                    {" — "}{t(PAIN_DESCRIPTIONS[Math.round(log.periodInfo.cramps)])}\n                  </span>\n                </p>\n              )}\n              {log?.periodInfo?.discharge && (\n                <p className="mt-2 text-xs leading-relaxed text-muted-foreground">\n                  <span className="font-semibold text-foreground">{t("Discharge")}:</span>{" "}\n                  {t(log.periodInfo.discharge)}\n                  {log.periodInfo.dischargeNote ? ` — ${log.periodInfo.dischargeNote}` : ""}\n                </p>\n              )}\n              {log?.periodInfo?.note && (\n                <p className="mt-2 text-sm whitespace-pre-line">\n                  <span className="font-semibold">{t("Note")}:</span> {log.periodInfo.note}\n                </p>\n              )}\n              <p className="mt-1 text-[10px] text-primary">{t("Tap to edit")}</p>\n            </button>\n          </Card>'''
if old not in s: raise SystemExit('blueberry block not found')
s=s.replace(old,new,1)
s=s.replace('{p.note && <p className="mt-1 text-sm whitespace-pre-line">"{p.note}"</p>}', '{p.note && <p className="mt-2 text-sm whitespace-pre-line"><span className="font-semibold">{t("Note")}:</span> {p.note}</p>}',1)
s=s.replace('{entry.note ? <p className="mt-1 whitespace-pre-line text-sm">{entry.note}</p> : null}', '{entry.note ? <p className="mt-1 whitespace-pre-line text-sm"><span className="font-semibold">{t("Note")}:</span> {entry.note}</p> : null}',2)
p.write_text(s)
