-- Legal-consent record and deliberately content-free product analytics.
-- Existing health tables, calculations and sharing semantics are unchanged.

create table if not exists public.user_legal_consents (
  user_id uuid primary key references auth.users(id) on delete cascade,
  terms_version text not null,
  terms_accepted_at timestamptz not null,
  privacy_version text not null,
  privacy_acknowledged_at timestamptz not null,
  health_consent_version text not null,
  health_consent_at timestamptz not null,
  health_consent_withdrawn_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.user_legal_consents enable row level security;
revoke all on public.user_legal_consents from anon;
revoke all on public.user_legal_consents from authenticated;
grant select, insert, update on public.user_legal_consents to authenticated;

drop policy if exists "users_read_own_legal_consent" on public.user_legal_consents;
create policy "users_read_own_legal_consent"
on public.user_legal_consents for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "users_insert_own_legal_consent" on public.user_legal_consents;
create policy "users_insert_own_legal_consent"
on public.user_legal_consents for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "users_update_own_legal_consent" on public.user_legal_consents;
create policy "users_update_own_legal_consent"
on public.user_legal_consents for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create table if not exists public.product_analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('onboarding_started', 'onboarding_completed', 'account_created')),
  occurred_at timestamptz not null default now()
);

alter table public.product_analytics_events enable row level security;
revoke all on public.product_analytics_events from anon;
revoke all on public.product_analytics_events from authenticated;
grant insert on public.product_analytics_events to authenticated;

drop policy if exists "authenticated_insert_content_free_product_event" on public.product_analytics_events;
create policy "authenticated_insert_content_free_product_event"
on public.product_analytics_events for insert to authenticated
with check (event_name in ('onboarding_started', 'onboarding_completed', 'account_created'));

create index if not exists product_analytics_events_event_time_idx
on public.product_analytics_events (event_name, occurred_at desc);
