// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { guardCloudAccountOwnership } from '@/lib/cloudAccountOwnership';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_');
}

export function assertBrowserSafeSupabaseKey(value: string): void {
  if (value.startsWith('sb_secret_')) {
    throw new Error('Refusing to initialize the BIXBO browser client with a Supabase secret key.');
  }
}

type RecentWrite = {
  at: number;
  status: number;
  statusText: string;
  headers: [string, string][];
};

const WRITE_DEDUPE_WINDOW_MS = 15_000;
const inFlightWrites = new Map<string, Promise<Response>>();
const recentSuccessfulWrites = new Map<string, RecentWrite>();

export const BIXBO_AUTH_STORAGE_KEY = 'bixbo:supabase-auth:v1';
const CANONICAL_LEGACY_AUTH_STORAGE_KEY = 'sb-wgdydwttzsveevkljkmr-auth-token';

function legacyAuthStorageKeys(supabaseUrl: string): string[] {
  const keys = new Set<string>([CANONICAL_LEGACY_AUTH_STORAGE_KEY]);
  try {
    const hostname = new URL(supabaseUrl).hostname;
    if (hostname.endsWith('.supabase.co')) {
      const projectRef = hostname.slice(0, -'.supabase.co'.length);
      if (projectRef) keys.add(`sb-${projectRef}-auth-token`);
    }
  } catch {
    // A malformed URL will fail client initialization below; auth migration is best-effort.
  }
  return [...keys];
}

function storedSessionExpiry(value: string | null): number {
  if (!value) return 0;
  try {
    const parsed = JSON.parse(value) as { expires_at?: unknown };
    const expiresAt = Number(parsed?.expires_at);
    return Number.isFinite(expiresAt) ? expiresAt : 0;
  } catch {
    return 0;
  }
}

function createPersistentAuthStorage(supabaseUrl: string) {
  const storage = window.localStorage;
  const legacyKeys = legacyAuthStorageKeys(supabaseUrl);

  const clearLegacyKeys = () => {
    for (const legacyKey of legacyKeys) storage.removeItem(legacyKey);
  };

  return {
    getItem(key: string): string | null {
      if (key !== BIXBO_AUTH_STORAGE_KEY) return storage.getItem(key);

      const current = storage.getItem(BIXBO_AUTH_STORAGE_KEY);
      let freshest = current;
      let freshestExpiry = storedSessionExpiry(current);

      for (const legacyKey of legacyKeys) {
        const legacyValue = storage.getItem(legacyKey);
        if (legacyValue == null) continue;

        const legacyExpiry = storedSessionExpiry(legacyValue);
        if (freshest == null || legacyExpiry > freshestExpiry) {
          freshest = legacyValue;
          freshestExpiry = legacyExpiry;
        }
      }

      if (freshest != null) storage.setItem(BIXBO_AUTH_STORAGE_KEY, freshest);

      // A rotating Supabase refresh-token session must have one persisted owner.
      // Keeping the same session under both the current and legacy keys lets
      // different PWA/tab versions refresh independently and can make Supabase
      // revoke the whole session as refresh-token reuse.
      clearLegacyKeys();

      return freshest;
    },
    setItem(key: string, value: string): void {
      storage.setItem(key, value);
      if (key !== BIXBO_AUTH_STORAGE_KEY) return;

      // Do not mirror rotating refresh tokens to the old Supabase key. One
      // canonical storage key keeps every current BIXBO client on one token chain.
      clearLegacyKeys();
    },
    removeItem(key: string): void {
      storage.removeItem(key);
      if (key !== BIXBO_AUTH_STORAGE_KEY) return;
      clearLegacyKeys();
    },
  };
}

function requestUrl(input: RequestInfo | URL): URL | null {
  try {
    const raw = typeof input === 'string'
      ? input
      : input instanceof URL
        ? input.href
        : input.url;
    return new URL(raw);
  } catch {
    return null;
  }
}

function requestMethod(input: RequestInfo | URL, init?: RequestInit): string {
  if (init?.method) return init.method.toUpperCase();
  if (typeof Request !== 'undefined' && input instanceof Request) return input.method.toUpperCase();
  return 'GET';
}

function bodyFingerprint(body: BodyInit | null | undefined): string | null {
  if (typeof body !== 'string') return null;
  let hash = 2166136261;
  for (let index = 0; index < body.length; index += 1) {
    hash ^= body.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return `${body.length}:${(hash >>> 0).toString(36)}`;
}

function dedupeKey(input: RequestInfo | URL, init?: RequestInit): string | null {
  const method = requestMethod(input, init);
  if (method !== 'POST' && method !== 'PUT' && method !== 'PATCH') return null;

  const url = requestUrl(input);
  if (!url || url.pathname !== '/rest/v1/user_data' && url.pathname !== '/rest/v1/partner_shared_data') return null;

  const headers = new Headers(init?.headers);
  const prefer = headers.get('prefer') ?? '';
  // Never synthesize a response for calls that explicitly need a returned row.
  if (/return\s*=\s*representation/i.test(prefer)) return null;

  const fingerprint = bodyFingerprint(init?.body);
  return fingerprint ? `${method}:${url.origin}${url.pathname}?${url.searchParams.toString()}:${fingerprint}` : null;
}

function cloneStoredResponse(stored: RecentWrite): Response {
  return new Response(null, {
    status: stored.status,
    statusText: stored.statusText,
    headers: stored.headers,
  });
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    const nextInit = { ...init, headers };
    const key = dedupeKey(input, nextInit);

    if (!key) return fetch(input, nextInit);

    const now = Date.now();
    const recent = recentSuccessfulWrites.get(key);
    if (recent && now - recent.at <= WRITE_DEDUPE_WINDOW_MS) {
      return Promise.resolve(cloneStoredResponse(recent));
    }
    if (recent) recentSuccessfulWrites.delete(key);

    const active = inFlightWrites.get(key);
    if (active) return active.then((response) => response.clone());

    const request = fetch(input, nextInit)
      .then((response) => {
        if (response.ok) {
          recentSuccessfulWrites.set(key, {
            at: Date.now(),
            status: response.status,
            statusText: response.statusText,
            headers: [...response.headers.entries()],
          });
        }
        return response;
      })
      .finally(() => {
        inFlightWrites.delete(key);
      });

    inFlightWrites.set(key, request);
    return request.then((response) => response.clone());
  };
}

function createSupabaseClient() {
  // BIXBO-owned Supabase project. Environment variables can still override
  // these values at build time, e.g. in Cloudflare.
  const PUBLIC_SUPABASE_URL = "https://wgdydwttzsveevkljkmr.supabase.co";
  const PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable__K7x0Rsn4e7lT4Ut3_g04A_8w_WTaH3";
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || PUBLIC_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || PUBLIC_SUPABASE_PUBLISHABLE_KEY;

  assertBrowserSafeSupabaseKey(SUPABASE_PUBLISHABLE_KEY);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storageKey: BIXBO_AUTH_STORAGE_KEY,
      storage: typeof window !== 'undefined' ? createPersistentAuthStorage(SUPABASE_URL) : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    }
  });

  if (typeof window !== 'undefined') {
    let reloadScheduled = false;
    client.auth.onAuthStateChange((_event, session) => {
      const userId = session?.user?.id;
      if (!userId) return;

      const ownership = guardCloudAccountOwnership(userId);
      if (ownership !== 'switched' || reloadScheduled) return;

      reloadScheduled = true;
      window.setTimeout(() => window.location.reload(), 0);
    });
  }

  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});